version: "3.8"

services:
  backend:
    container_name: skrepai_backend_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3051:3051"
    environment:
      - MONGODB_URL=mongodb://root:examplepassword@mongo:27017
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      - skrepai_shared_network
  mongo:
    container_name: skrepai_mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=examplepassword
    volumes:
      - mongodb-data:/data/db  # Renaming the volume
    networks:
      - skrepai_shared_network

volumes:
  mongodb-data:

networks:
  skrepai_shared_network:
    driver: bridge